services:
  # C# onlineedu-api service
  onlineedu-api:
    # Build context points to the 'backend' directory
    build:
      context: ./backend/src
      dockerfile: Dockerfile
    container_name: onlineedu-api
    # restart: always
    ports:
      # Map host ports to container ports
      - "8000:8080"
    environment:
      # Use .env file for sensitive information like AWS keys and API keys
      - ASPNETCORE_URLS=http://+:8080
      - ASPNETCORE_ENVIRONMENT=Production
    volumes:
      # This line creates a named volume to persist the keys
      - weatherapi-keys:/root/.aspnet/DataProtection-Keys

  # React front-end service
  web:
    build:
      context: ./front
      dockerfile: Dockerfile
    container_name: web
    ports:
      - "80:80" # Map host port 3000 to container port 80 (Nginx)
    depends_on:
      - onlineedu-api # Optional: wait for backend

# Define the named volume at the bottom of the file
volumes:
  weatherapi-keys:
