@startuml AdminUseCases

left to right direction

actor Admin as admin

package "Online Education Platform" {
    usecase "Login" as UC1
    usecase "Logout" as UC2
    usecase "Users Management " as UC4
    usecase "Lesson Management" as UC5
    usecase "Send Notifications" as UC7

    usecase "User CRUD" as UC8
    usecase "Approve Lesson" as UC9
    usecase "Reject Lesson" as UC10
}

admin --> UC7 
admin --> UC5
admin --> UC1
admin --> UC2
admin --> UC4 


UC4 ..> UC8 : <<include>>
UC5 ..> UC9 : <<include>>
UC5 ..> UC10 : <<include>>

@enduml