
1. Student Use Case Diagram

@startuml StudentUseCases

left to right direction

actor Student as student

package "Online Education Platform" {
    usecase "Login" as UC1
    usecase "Logout" as UC2
    usecase "Browse Course" as UC3
    usecase "Book Lesson" as UC4
    usecase "View Lesson" as UC5
    usecase "Cancel Lesson" as UC6
    usecase "Enter Classroom" as UC7

    usecase "Chat" as UC8
    usecase "View Notification" as UC9
}

student --> UC1
student --> UC2
student --> UC3
UC3 ..> UC4 : <<include>>

student --> UC5
UC5 ..> UC6 : <<include>>
UC5 ..> UC7 : <<include>>
UC7 ..> UC8 : <<include>>
student --> UC9


@enduml