@startuml TeacherUseCases

left to right direction

actor Teacher as teacher

package "Online Education Platform" {

    usecase "Login" as UC2
    usecase "Logout" as UC3
    usecase "Course Management" as UC4
    usecase "Course CRUD" as UC5
    usecase "Schedule Management" as UC6
    usecase "View Schedule" as UC7
    usecase "Update Schedule" as UC8

    usecase "View Booking" as UC9
    usecase "Start CLass" as UC10
     usecase "View Notification" as UC11
}

teacher --> UC2
teacher --> UC3
teacher --> UC4
UC4 ..> UC5 : <<include>>
teacher --> UC6
UC6 ..> UC7 : <<include>>
UC6 ..>  UC8 : <<include>>

teacher --> UC9
UC9 ..>  UC10 : <<include>>

teacher --> UC11

@enduml